export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const API_ERROR = "LOGIN_API_ERROR"
export const API_MESSAGE = "LOGIN_API_MESSAGE"
export const SOCIAL_LOGIN = "SOCIAL_LOGIN"
